In [1]:
import requests
import pandas as pd
from haversine import haversine, Unit

In [2]:
df_carpark = pd.read_csv('carParkLocation.csv')
df_carpark

,Unnamed: 0,CarParkID,display_name,Latitude,Longitude,Development,Location,AvailableLots,LotType,Agency
0,0,5,"Millenia Tower, 1, Temasek Avenue, Suntec City...",1.292510,103.860090,Millenia Singapore,1.29251 103.86009,777,C,LTA
1,1,A0017,"Arab Street, Little India, Rochor, Singapore, ...",1.302942,103.857025,ARAB STREET - QUEEN STREET OFF STREET,1.3029418442251717 103.8570252731165,0,Y,URA
2,2,C0162,"Fort Canning Park, Central Expressway, Museum,...",1.293973,103.844517,CLEMENCEAU AVENUE OFF STREET,1.2939732461823374 103.84451675349408,0,Y,URA
3,3,D0006,"Duxton Hill Car Park, Duxton Hill, Chinatown, ...",1.279121,103.843077,DUXTON HILL OFF STREET,1.279121361423107 103.84307668605454,0,C,URA
4,4,D0026,"Little India, Queen Street Terminal, Selegie, ...",1.305896,103.853567,DICKSON ROAD OFF STREET,1.305896126598381 103.85356732694177,0,C,URA
...,...,...,...,...,...,...,...,...,...,...
494,495,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,0,H,HDB
495,496,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,33,Y,HDB
496,497,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,200,C,HDB
497,498,CAM,"Commonwealth View, 88, Tanglin Halt Road, Quee...",1.301821,103.798206,BLK 88 TANGLIN HALT RD,1.3018210574302524 103.79820565809396,50,H,HDB
498,499,CAM,"Commonwealth View, 88, Tanglin Halt Road, Quee...",1.301821,103.798206,BLK 88 TANGLIN HALT RD,1.3018210574302524 103.79820565809396,98,Y,HDB

In [3]:
df_rates = pd.read_csv('carparkrates_withlatlon.csv')
df_rates

,Unnamed: 0.1,Unnamed: 0,Car Park,Weekdays before 5/6pm,Weekdays after 5/6pm,Saturdays,Sundays/Public Holidays,latitude,longitude
0,0,0,22 Bideford Road,7am-4.59pm: $3 for 1st hr; $1.50 for sub. 30mi...,5pm-6.59am: $4.50 per entry.,7am-4.59pm: $3 for 1st hr; $1.50 for sub. 30mi...,7am-4.59pm: $3 for 1st hr; $1.50 for sub. 30mi...,1.303527,103.836921
1,1,1,313@Somerset,Monday to Thursday: 7am-7am: $3.05 for 1st hr;...,-,Friday to Sunday and Public Holiday: 7am-7am: ...,Friday to Sunday and Public Holiday: 7am-7am: ...,1.301045,103.838579
2,2,2,50 Scotts Road; Singapore 228242,7am-10.59am/2pm- 4.59pm: $2.50 for 1st hr; $1....,5pm-6.59am: $3.50 per entry.,$3.50 per entry,$3.50 per entry,1.310919,103.837119
3,3,3,51 Cuppage Road (Formerly Starhub Centre),7am-7am: $2.80 for 1st hr; $1.20 for sub. 30mi...,7am-7am: $2.80 for 1st hr; $1.20 for sub. 30mi...,7am-7am: $2.80 for 1st hr; $1.20 for sub. 30mi...,7am-7am: $2.80 for 1st hr; $1.20 for sub. 30mi...,1.302859,103.840171
4,4,4,Angullia Park Off-Street,7am-11am: $1.30/30min (Per Minute Charging); 1...,5pm-10.30pm: $0.80/30min (Per Minute Charging)...,Same as Weekdays,7am to 11am : $0.70/30min; 11am to 10.30pm: $0...,1.304096,103.829785
...,...,...,...,...,...,...,...,...,...
378,378,378,Swissotel The Stamford Hotel,8am-6pm: $2.20 for 1st hr; $0.55 for sub. 15mins,Aft 6pm-8am next day: $3 per entry,"8am-8am next day: $2.20 for 1st 2hrs, $0.40 fo...","8am-8am next day: $2.20 for 1st 2hrs, $0.40 fo...",1.293277,103.853508
379,379,379,The Ritz-Carlton Millenia Singapore,7am-6pm: $3.40 for 1st hr; $1.20 for sub.Â½ hr,6pm-7am next day: $2.30 per entry,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,1.290969,103.860121
380,380,380,Village Hotel Katong (Ex Paramount Hotel),Daily: $1.08 per hr,-,-,-,1.305967,103.904956
381,381,381,York Hotel,8.01am-6pm: $3 for 1st hr; $1.50 for sub. 30min,6pm-8am: $4 per entry,8.01am-6pm: $3 for 1st hr; $1.50 for sub. 30min,$4 per entry,NaN,NaN
382,382,382,Yotel Singapore (shared carpark with Internati...,7am-6pm: $3 for 1st hr or part thereof.; $1.50...,6pm-7am: $4 per entry,7am-6pm: $3 for 1st hr or part thereof.; $1.50...,7am-6pm: $3 for 1st hr or part thereof.; $1.50...,1.306165,103.831000

In [ ]:
# # df_rates['latitude'], df_rates['longitude'] = zip(*df_rates['car_park'].apply(lambda x: get_lat_long(x, 'YOUR_API_KEY_HERE')))
# count = 0
# for index, row in df_rates.iterrows():
#     location = row['Car Park']
#     latitude, longitude = get_lat_long(location, api_key)
#     df_rates.at[index, 'latitude'] = latitude
#     df_rates.at[index, 'longitude'] = longitude
#     count = count + 1
#     print("{} = {}, {}".format(count, latitude, longitude))
#     if count >= 400:
#         break

# df_rates.to_csv("carparkrates_withlatlon.csv")

In [4]:
# Function to calculate distance
def calculate_distance(row, rate_row):
    coords_1 = (row['Latitude'], row['Longitude'])
    coords_2 = (rate_row['latitude'], rate_row['longitude'])
    return haversine(coords_1, coords_2, unit = Unit.MILES)

def find_closest_carpark(row, df_rates):
    distances = df_rates.apply(lambda rate_row: calculate_distance(row, rate_row), axis=1)
    closest_index = distances.idxmin()
    return df_rates.loc[closest_index]

closest_carparks = df_carpark.apply(lambda row: find_closest_carpark(row, df_rates), axis=1)
df_carpark['Price_Weekdays_before_5_6pm'] = closest_carparks['Weekdays  before 5/6pm']
df_carpark['Price_Weekdays_after_5_6pm'] = closest_carparks['Weekdays  after 5/6pm']
df_carpark['Price_Saturdays'] = closest_carparks['Saturdays']
df_carpark['Price_Sundays_Public_Holiday'] = closest_carparks['Sundays/Public Holidays']

In [5]:
df_carpark

,Unnamed: 0,CarParkID,display_name,Latitude,Longitude,Development,Location,AvailableLots,LotType,Agency,Price_Weekdays_before_5_6pm,Price_Weekdays_after_5_6pm,Price_Saturdays,Price_Sundays_Public_Holiday
0,0,5,"Millenia Tower, 1, Temasek Avenue, Suntec City...",1.292510,103.860090,Millenia Singapore,1.29251 103.86009,777,C,LTA,7am-6pm: $3.40 for 1st hr; $1.20 per sub.Â½ hr,6pm to 7am: $2.30 per entry,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...
1,1,A0017,"Arab Street, Little India, Rochor, Singapore, ...",1.302942,103.857025,ARAB STREET - QUEEN STREET OFF STREET,1.3029418442251717 103.8570252731165,0,Y,URA,8am-5pm: $2.35 for 1st hr $1.07 for sub Â½ hr. ...,Aft 5pm: $2.68 per entry.,8am-5pm: $2.35 for 1st hr $1.07 for sub Â½ hr. ...,8am-8am the following day: $2.68 per entry.
2,2,C0162,"Fort Canning Park, Central Expressway, Museum,...",1.293973,103.844517,CLEMENCEAU AVENUE OFF STREET,1.2939732461823374 103.84451675349408,0,Y,URA,7am-5pm: $1.07 per hr,5pm-7am: $3.21 per entry,7am-1pm: $1.07 per hr; 1pm-7am next day: $3.21...,7am-1pm: $1.07 per hr; 1pm-7am next day: $3.21...
3,3,D0006,"Duxton Hill Car Park, Duxton Hill, Chinatown, ...",1.279121,103.843077,DUXTON HILL OFF STREET,1.279121361423107 103.84307668605454,0,C,URA,7am-5pm: $1.20/30 mins,5pm-7am the following day: $0.60/30 Mins. Char...,7am-5pm: $1.20/30 mins,7am-7am the next day: $0.60/30 mins. Charges c...
4,4,D0026,"Little India, Queen Street Terminal, Selegie, ...",1.305896,103.853567,DICKSON ROAD OFF STREET,1.305896126598381 103.85356732694177,0,C,URA,"7am-6pm: $2.00 for 1st hr, sub 30mins at $1.00...",6pm-12am: $3.00 per entry 12am to 7am: $1.00 p...,"7am-6pm: $2.00 for 1st hr, sub 30mins at $1.00...","7am-6pm: $2.00 for 1st hr, sub 30mins at $1.00..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,495,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,0,H,HDB,Daily: $1.70 for 1st hr or part thereof; $0.85...,-,-,-
495,496,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,33,Y,HDB,Daily: $1.70 for 1st hr or part thereof; $0.85...,-,-,-
496,497,C4M,413A Commonwealth Avenue West Multi Storey Car...,1.311480,103.770503,BLK 413A COMMONWEALTH AVENUE WEST,1.3114801086966732 103.77050251295184,200,C,HDB,Daily: $1.70 for 1st hr or part thereof; $0.85...,-,-,-
497,498,CAM,"Commonwealth View, 88, Tanglin Halt Road, Quee...",1.301821,103.798206,BLK 88 TANGLIN HALT RD,1.3018210574302524 103.79820565809396,50,H,HDB,Mon-Thurs: 12am-9pm: $2.40 per 30min or part t...,Mon-Thurs: 9pm-12am: $5 per entry,Friday/Saturday & eve of PH: 12am-9pm: $2.40 p...,Friday/Saturday & eve of PH: 12am-9pm: $2.40 p...
498,499,CAM,"Commonwealth View, 88, Tanglin Halt Road, Quee...",1.301821,103.798206,BLK 88 TANGLIN HALT RD,1.3018210574302524 103.79820565809396,98,Y,HDB,Mon-Thurs: 12am-9pm: $2.40 per 30min or part t...,Mon-Thurs: 9pm-12am: $5 per entry,Friday/Saturday & eve of PH: 12am-9pm: $2.40 p...,Friday/Saturday & eve of PH: 12am-9pm: $2.40 p...

In [6]:
df_rates[df_rates['Car Park'].str.contains('Millenia', case=False)]

,Unnamed: 0.1,Unnamed: 0,Car Park,Weekdays before 5/6pm,Weekdays after 5/6pm,Saturdays,Sundays/Public Holidays,latitude,longitude
220,220,220,Millenia Singapore (Basement Car Park),7am-6pm: $3.40 for 1st hr; $1.20 per sub.Â½ hr,6pm to 7am: $2.30 per entry,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...,1.292072,103.859851
221,221,221,Millenia Walk (Basement Car Park),7am-6pm: $3.40 for 1st hr; $1.20 per sub.Â½ hr,6pm to 7am: $2.30 per entry,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...,7am to 7am next day: $2.30 for 1st 2hrs; $1.20...,NaN,NaN
222,222,222,Millenia Walk (Surface parking @ L1),7am-6pm: $6.70 for 1st Â½ hr; $2.30 every sub. 1hr,6pm-7am: $6.70 for 1st 2hrs; $2.30 every sub.1hr,7am-7am (next day): $6.70 for 1st 2hrs; $2.30 ...,7am-7am (next day): $6.70 for 1st 2hrs; $2.30 ...,1.291659,103.859763
274,274,274,The Ritz-Carlton Millenia Singapore,7am-6pm: $3.40 for 1st hr; $1.20 for sub.Â½ hr,6pm-7am next day: $2.30 per entry,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,1.290969,103.860121
379,379,379,The Ritz-Carlton Millenia Singapore,7am-6pm: $3.40 for 1st hr; $1.20 for sub.Â½ hr,6pm-7am next day: $2.30 per entry,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,7am-7am (next day): $2.30 for 1st 2hrs; $1.20 ...,1.290969,103.860121

In [7]:
df_rates[df_rates['Car Park'].str.contains('313', case=False)]

,Unnamed: 0.1,Unnamed: 0,Car Park,Weekdays before 5/6pm,Weekdays after 5/6pm,Saturdays,Sundays/Public Holidays,latitude,longitude
1,1,1,313@Somerset,Monday to Thursday: 7am-7am: $3.05 for 1st hr;...,-,Friday to Sunday and Public Holiday: 7am-7am: ...,Friday to Sunday and Public Holiday: 7am-7am: ...,1.301045,103.838579

In [8]:
df_carpark[df_carpark['display_name'].str.contains('313', case=False)]

,Unnamed: 0,CarParkID,display_name,Latitude,Longitude,Development,Location,AvailableLots,LotType,Agency,Price_Weekdays_before_5_6pm,Price_Weekdays_after_5_6pm,Price_Saturdays,Price_Sundays_Public_Holiday
219,220,24,"313@Somerset, 313, Orchard Road, Orchard, Sing...",1.30084,103.83872,313@Somerset,1.30084 103.83872,87,C,LTA,Monday to Thursday: 7am-7am: $3.05 for 1st hr;...,-,Friday to Sunday and Public Holiday: 7am-7am: ...,Friday to Sunday and Public Holiday: 7am-7am: ...

In [9]:
df_carpark.to_csv('carParkLocation_withPrice.csv')